export {
  SUPPORTED_CRS,
  WGS84,
  coordinateResults,
  decodeGars,
  decodeGeoref,
  decodeMgrs,
  directGeodesic,
  encodeGars,
  encodeGeoref,
  encodeMgrs,
  formatDdm,
  formatDms,
  fromDdm,
  fromDecimalDegrees,
  fromDms,
  fromGars,
  fromGeoref,
  fromMgrs,
  fromUtmUps,
  inverseGeodesic,
  measureGeodesicPolyline,
  normalizeEpsg,
  transformCrs,
  utmUpsForward,
  utmUpsInverse,
} from "../index.js";
export type {
  DirectGeodesicResult,
  Ellipsoid,
  GeodesicOptions,
  GeodesicResult,
  GeoPoint,
  NumericGeoPoint,
  PolylineMeasurement,
} from "../index.js";
