export const COPY = {
  tr: {
    language: "Dil",
    units: "Uzunluk",
    coordinates: "Koordinatlar",
    unitTitle: "Uzunluk Çevirici",
    unitSubtitle: "Değeri girin ve iki uzunluk birimini seçin.",
    value: "Değer",
    result: "Sonuç",
    from: "Kaynak birim",
    to: "Hedef birim",
    swap: "Birimleri değiştir",
    copy: "Kopyala",
    copied: "Kopyalandı",
    exact: "Tam sonuç",
    rounded: "24 haneye yuvarlandı",
    rate: "Oran",
    swapPrecision:
      "Birimleri değiştirdiğinizde kesin iç değer korunur; gösterim yuvarlaması hesaba geri taşınmaz.",
    examples: "Örnekler",
    examplesHint: "Kullanmak için bir örneğe tıklayın.",
    invalid: "Geçerli bir sayı girin.",
    unitFooter: "Uzunluk dönüşümleri kesin kesir oranlarıyla hesaplanır.",
    coordinateTitle: "Koordinat Çevirici",
    coordinateSubtitle:
      "WGS 84 konum formatları, EPSG dönüşümleri ve elipsoidal mesafe.",
    positionFormats: "Konum formatları",
    crs: "CRS / EPSG",
    distance: "Mesafe",
    inputFormat: "Girdi formatı",
    precision: "MGRS hassasiyeti",
    convert: "Dönüştür",
    latitude: "Enlem",
    longitude: "Boylam",
    zone: "Zon",
    hemisphere: "Yarımküre",
    easting: "Doğu değeri",
    northing: "Kuzey değeri",
    coordinateValue: "Koordinat",
    outputFormats: "Tüm çıktılar",
    resolutionCell: "hücre",
    resolutionMaximum: "çıktı yuvarlaması",
    resolutionPerAxis: "eksen başına",
    coordinateInvalid:
      "Koordinat okunamadı. Formatı ve değer aralıklarını kontrol edin.",
    wgs84: "Datum: WGS 84",
    pointSource: "Girdi bir noktayı temsil eder.",
    cellSource: "Çıktılar, girdi hücresinin merkez noktasına aittir.",
    areaSource:
      "GARS bir alan referansıdır; navigasyon veya hedefleme için kullanılmamalıdır.",
    sourceCrs: "Kaynak CRS",
    targetCrs: "Hedef CRS",
    transform: "Dönüştür",
    swapCrs: "Sonucu tersine çevir",
    crsInvalid:
      "Dönüşüm yapılamadı. EPSG kodlarını ve X/Y değerlerini kontrol edin.",
    axisNote:
      "X/Y sırası kullanılır. EPSG:4326 için X = boylam, Y = enlem.",
    availableEpsg:
      "Hazır tanımlar: WGS 84, Web Mercator, UTM zonları ve UPS.",
    startPoint: "Başlangıç noktası",
    endPoint: "Bitiş noktası",
    startLatitude: "Başlangıç enlemi",
    startLongitude: "Başlangıç boylamı",
    endLatitude: "Bitiş enlemi",
    endLongitude: "Bitiş boylamı",
    measure: "Ölç",
    metres: "Metre",
    kilometres: "Kilometre",
    nauticalMiles: "Deniz mili",
    bearings: "Başlangıç → varış azimutu",
    measurementResult: "Mesafe sonucu",
    measurementReady: "Mesafe ve harita çizgisi güncellendi.",
    measurementCleared:
      "Koordinatlar değişti. Önceki sonuç ve harita çizgisi temizlendi.",
    distanceInvalid:
      "Mesafe hesaplanamadı. Enlem ve boylam değerlerini kontrol edin.",
    coordinateRange: "Enlem ±90°, boylam ±180°",
    distanceModel:
      "WGS 84 elipsoidi üzerindeki en kısa yüzey yolu hesaplanır; yükseklik ve arazi eğimi dahil değildir.",
    calculationDetails: "Hesaplama ayrıntıları",
    shortestGeodesic: "en kısa elipsoidal yol",
    solver: "Çözücü",
    iterations: "İterasyon",
    mapSegments: "Çizgi parçası",
    googleSphereDifference: "küresel model; sonuç farklı olabilir",
    ambiguousPath:
      "Bu iki nokta için en kısa yol tek değildir. Haritada kararlı bir temsil yolu gösterilir.",
    mapTitle: "Ölçüm haritası",
    mapVisualOnly:
      "Çizgi çekirdekte hesaplanır; harita yalnızca sonucu gösterir.",
    mapFit: "Hattı göster",
    mapModel: "Hesaplama modeli",
    mapNoTerrain: "Arazi yüksekliği hariç",
    mapLoading: "Harita hazırlanıyor…",
    mapUnavailable:
      "Harita görüntülenemedi. Mesafe hesaplama kullanılmaya devam edebilir.",
    mapEmpty: "Haritada gösterilecek güncel ölçüm yok.",
    mapStart: "Başlangıç A",
    mapEnd: "Bitiş B",
    mapDistance: "Elipsoidal mesafe",
    coordinateFooter:
      "Dönüşümler ve ölçümler çevrimdışı çalışır; sonuçlar kullanım amacına uygun kaynakla doğrulanmalıdır.",
  },
  en: {
    language: "Language",
    units: "Length",
    coordinates: "Coordinates",
    unitTitle: "Length Converter",
    unitSubtitle: "Enter a value and select two length units.",
    value: "Value",
    result: "Result",
    from: "From",
    to: "To",
    swap: "Swap units",
    copy: "Copy",
    copied: "Copied",
    exact: "Exact result",
    rounded: "Rounded to 24 digits",
    rate: "Rate",
    swapPrecision:
      "Swapping units preserves the exact internal value; display rounding is not fed back into the calculation.",
    examples: "Examples",
    examplesHint: "Click an example to use it.",
    invalid: "Enter a valid number.",
    unitFooter: "Length conversions are calculated with exact fractional ratios.",
    coordinateTitle: "Coordinate Converter",
    coordinateSubtitle:
      "WGS 84 position formats, EPSG transformations and ellipsoidal distance.",
    positionFormats: "Position formats",
    crs: "CRS / EPSG",
    distance: "Distance",
    inputFormat: "Input format",
    precision: "MGRS precision",
    convert: "Convert",
    latitude: "Latitude",
    longitude: "Longitude",
    zone: "Zone",
    hemisphere: "Hemisphere",
    easting: "Easting",
    northing: "Northing",
    coordinateValue: "Coordinate",
    outputFormats: "All outputs",
    resolutionCell: "cell",
    resolutionMaximum: "output rounding",
    resolutionPerAxis: "per axis",
    coordinateInvalid:
      "The coordinate could not be read. Check its format and ranges.",
    wgs84: "Datum: WGS 84",
    pointSource: "The input represents a point.",
    cellSource: "Outputs refer to the center point of the input cell.",
    areaSource:
      "GARS is an area reference and must not be used for navigation or targeting.",
    sourceCrs: "Source CRS",
    targetCrs: "Target CRS",
    transform: "Transform",
    swapCrs: "Reverse the result",
    crsInvalid:
      "The transformation failed. Check the EPSG codes and X/Y values.",
    axisNote:
      "X/Y order is used. For EPSG:4326, X = longitude and Y = latitude.",
    availableEpsg:
      "Built-in definitions: WGS 84, Web Mercator, UTM zones and UPS.",
    startPoint: "Start point",
    endPoint: "End point",
    startLatitude: "Start latitude",
    startLongitude: "Start longitude",
    endLatitude: "End latitude",
    endLongitude: "End longitude",
    measure: "Measure",
    metres: "Metres",
    kilometres: "Kilometres",
    nauticalMiles: "Nautical miles",
    bearings: "Initial → final bearing",
    measurementResult: "Distance result",
    measurementReady: "The distance and map line were updated.",
    measurementCleared:
      "The coordinates changed. The previous result and map line were cleared.",
    distanceInvalid:
      "The distance could not be calculated. Check the latitude and longitude values.",
    coordinateRange: "Latitude ±90°, longitude ±180°",
    distanceModel:
      "Uses the shortest surface path on the WGS 84 ellipsoid; elevation and terrain slope are not included.",
    calculationDetails: "Calculation details",
    shortestGeodesic: "shortest ellipsoidal path",
    solver: "Solver",
    iterations: "Iterations",
    mapSegments: "Line segments",
    googleSphereDifference: "spherical model; results can differ",
    ambiguousPath:
      "The shortest path is not unique for these points. The map shows a stable representative path.",
    mapTitle: "Measurement map",
    mapVisualOnly:
      "The core calculates the line; the map only displays the result.",
    mapFit: "Show line",
    mapModel: "Calculation model",
    mapNoTerrain: "Terrain elevation excluded",
    mapLoading: "Preparing the map…",
    mapUnavailable:
      "The map could not be displayed. Distance calculation remains available.",
    mapEmpty: "There is no current measurement to display on the map.",
    mapStart: "Start A",
    mapEnd: "End B",
    mapDistance: "Ellipsoidal distance",
    coordinateFooter:
      "Conversions and measurements work offline; verify results against a source appropriate for the intended use.",
  },
};

export const LENGTH_UNIT_LABELS = {
  en: {
    millimetre: "Millimetre",
    centimetre: "Centimetre",
    metre: "Metre",
    kilometre: "Kilometre",
    inch: "Inch",
    foot: "Foot",
    yard: "Yard",
    mile: "Mile",
    "nautical-mile": "Nautical mile",
  },
};

export const LENGTH_EXAMPLES = [
  { value: "1", from: "nautical-mile", to: "metre" },
  { value: "1", from: "foot", to: "metre" },
  { value: "1", from: "mile", to: "kilometre" },
];

export const COORDINATE_FORMATS = [
  { id: "dd", label: "DD" },
  { id: "dms", label: "DMS" },
  { id: "ddm", label: "DDM" },
  { id: "mgrs", label: "MGRS" },
  { id: "utm", label: "UTM / UPS" },
  { id: "gars", label: "GARS" },
  { id: "georef", label: "GEOREF" },
];

export const OUTPUT_FORMATS = [
  ["dd", "DD"],
  ["dms", "DMS"],
  ["ddm", "DDM"],
  ["mgrs", "MGRS"],
  ["utmUps", "UTM / UPS"],
  ["gars", "GARS"],
  ["georef", "GEOREF"],
];
