export const COPY = {
  tr: {
    language: "Dil",
    units: "Birimler",
    coordinates: "Koordinatlar",
    unitTitle: "Birim Çevirici",
    unitSubtitle: "Değeri girin ve birimleri seçin.",
    value: "Değer",
    result: "Sonuç",
    from: "Kaynak birim",
    to: "Hedef birim",
    swap: "Birimleri değiştir",
    copy: "Kopyala",
    copied: "Kopyalandı",
    exact: "Tam sonuç",
    rounded: "24 haneye yuvarlandı",
    rate: "Oran",
    examples: "Örnekler",
    examplesHint: "Kullanmak için bir örneğe tıklayın.",
    invalid: "Geçerli bir sayı girin.",
    unitFooter: "Sonlu birim dönüşümleri kesin kesirlerle hesaplanır.",
    coordinateTitle: "Koordinat Çevirici",
    coordinateSubtitle:
      "WGS 84 konum formatları, EPSG dönüşümleri ve elipsoidal mesafe.",
    positionFormats: "Konum formatları",
    crs: "CRS / EPSG",
    distance: "Mesafe",
    inputFormat: "Girdi formatı",
    precision: "MGRS hassasiyeti",
    convert: "Dönüştür",
    latitude: "Enlem",
    longitude: "Boylam",
    zone: "Zon",
    hemisphere: "Yarımküre",
    easting: "Doğu değeri",
    northing: "Kuzey değeri",
    coordinateValue: "Koordinat",
    outputFormats: "Tüm çıktılar",
    coordinateInvalid:
      "Koordinat okunamadı. Formatı ve değer aralıklarını kontrol edin.",
    wgs84: "Datum: WGS 84",
    pointSource: "Girdi bir noktayı temsil eder.",
    cellSource: "Çıktılar, girdi hücresinin merkez noktasına aittir.",
    areaSource:
      "GARS bir alan referansıdır; navigasyon veya hedefleme için kullanılmamalıdır.",
    sourceCrs: "Kaynak CRS",
    targetCrs: "Hedef CRS",
    transform: "Dönüştür",
    crsInvalid:
      "Dönüşüm yapılamadı. EPSG kodlarını ve X/Y değerlerini kontrol edin.",
    axisNote:
      "X/Y sırası kullanılır. EPSG:4326 için X = boylam, Y = enlem.",
    availableEpsg:
      "Hazır tanımlar: WGS 84, Web Mercator, UTM zonları ve UPS.",
    startPoint: "Başlangıç noktası",
    endPoint: "Bitiş noktası",
    startLatitude: "Başlangıç enlemi",
    startLongitude: "Başlangıç boylamı",
    endLatitude: "Bitiş enlemi",
    endLongitude: "Bitiş boylamı",
    measure: "Ölç",
    metres: "Metre",
    kilometres: "Kilometre",
    nauticalMiles: "Deniz mili",
    bearings: "Başlangıç → varış azimutu",
    distanceInvalid:
      "Mesafe hesaplanamadı. Enlem ve boylam değerlerini kontrol edin.",
    distanceModel:
      "WGS 84 elipsoidi üzerindeki en kısa yüzey yolu hesaplanır; Web Mercator düzlem mesafesi kullanılmaz.",
    coordinateFooter:
      "Dönüşümler ve ölçümler çevrimdışı çalışır; sonuçlar kullanım amacına uygun kaynakla doğrulanmalıdır.",
  },
  en: {
    language: "Language",
    units: "Units",
    coordinates: "Coordinates",
    unitTitle: "Unit Converter",
    unitSubtitle: "Enter a value and select the units.",
    value: "Value",
    result: "Result",
    from: "From",
    to: "To",
    swap: "Swap units",
    copy: "Copy",
    copied: "Copied",
    exact: "Exact result",
    rounded: "Rounded to 24 digits",
    rate: "Rate",
    examples: "Examples",
    examplesHint: "Click an example to use it.",
    invalid: "Enter a valid number.",
    unitFooter: "Finite unit conversions are calculated with exact fractions.",
    coordinateTitle: "Coordinate Converter",
    coordinateSubtitle:
      "WGS 84 position formats, EPSG transformations and ellipsoidal distance.",
    positionFormats: "Position formats",
    crs: "CRS / EPSG",
    distance: "Distance",
    inputFormat: "Input format",
    precision: "MGRS precision",
    convert: "Convert",
    latitude: "Latitude",
    longitude: "Longitude",
    zone: "Zone",
    hemisphere: "Hemisphere",
    easting: "Easting",
    northing: "Northing",
    coordinateValue: "Coordinate",
    outputFormats: "All outputs",
    coordinateInvalid:
      "The coordinate could not be read. Check its format and ranges.",
    wgs84: "Datum: WGS 84",
    pointSource: "The input represents a point.",
    cellSource: "Outputs refer to the center point of the input cell.",
    areaSource:
      "GARS is an area reference and must not be used for navigation or targeting.",
    sourceCrs: "Source CRS",
    targetCrs: "Target CRS",
    transform: "Transform",
    crsInvalid:
      "The transformation failed. Check the EPSG codes and X/Y values.",
    axisNote:
      "X/Y order is used. For EPSG:4326, X = longitude and Y = latitude.",
    availableEpsg:
      "Built-in definitions: WGS 84, Web Mercator, UTM zones and UPS.",
    startPoint: "Start point",
    endPoint: "End point",
    startLatitude: "Start latitude",
    startLongitude: "Start longitude",
    endLatitude: "End latitude",
    endLongitude: "End longitude",
    measure: "Measure",
    metres: "Metres",
    kilometres: "Kilometres",
    nauticalMiles: "Nautical miles",
    bearings: "Initial → final bearing",
    distanceInvalid:
      "The distance could not be calculated. Check the latitude and longitude values.",
    distanceModel:
      "Uses the shortest surface path on the WGS 84 ellipsoid; Web Mercator planar distance is not used.",
    coordinateFooter:
      "Conversions and measurements work offline; verify results against a source appropriate for the intended use.",
  },
};

export const CATEGORY_LABELS = {
  en: {
    length: "Length",
    speed: "Speed",
    area: "Area",
    angle: "Angle",
    mass: "Mass",
    pressure: "Pressure",
    temperature: "Temperature",
  },
};

export const UNIT_LABELS = {
  en: {
    millimetre: "Millimetre",
    centimetre: "Centimetre",
    metre: "Metre",
    kilometre: "Kilometre",
    inch: "Inch",
    foot: "Foot",
    yard: "Yard",
    mile: "Mile",
    "nautical-mile": "Nautical mile",
    "metre-second": "Metres per second",
    "kilometre-hour": "Kilometres per hour",
    knot: "Knot",
    "mile-hour": "Miles per hour",
    "foot-second": "Feet per second",
    "square-metre": "Square metre",
    hectare: "Hectare",
    "square-kilometre": "Square kilometre",
    "square-foot": "Square foot",
    acre: "Acre",
    "square-nautical-mile": "Square nautical mile",
    degree: "Degree",
    gon: "Gon / grad",
    "nato-mil": "NATO mil",
    "wp-mil": "6000 mil",
    "minute-angle": "Minute of angle",
    "arc-second": "Arcsecond",
    milligram: "Milligram",
    gram: "Gram",
    kilogram: "Kilogram",
    tonne: "Metric tonne",
    ounce: "Ounce",
    pound: "Pound",
    pascal: "Pascal",
    kilopascal: "Kilopascal",
    hectopascal: "Hectopascal",
    bar: "Bar",
    atmosphere: "Standard atmosphere",
    psi: "Pound per square inch",
    celsius: "Celsius",
    kelvin: "Kelvin",
    fahrenheit: "Fahrenheit",
    rankine: "Rankine",
  },
};

export const UNIT_EXAMPLES = {
  length: [
    { value: "1", from: "nautical-mile", to: "metre" },
    { value: "1", from: "foot", to: "metre" },
    { value: "1", from: "mile", to: "kilometre" },
  ],
  speed: [
    { value: "1", from: "knot", to: "metre-second" },
    { value: "100", from: "kilometre-hour", to: "metre-second" },
    { value: "60", from: "mile-hour", to: "kilometre-hour" },
  ],
  area: [
    { value: "1", from: "square-nautical-mile", to: "square-kilometre" },
    { value: "1", from: "hectare", to: "square-metre" },
    { value: "1", from: "acre", to: "square-metre" },
  ],
  angle: [
    { value: "1600", from: "nato-mil", to: "degree" },
    { value: "1500", from: "wp-mil", to: "degree" },
    { value: "60", from: "minute-angle", to: "degree" },
  ],
  mass: [
    { value: "1", from: "pound", to: "kilogram" },
    { value: "1", from: "kilogram", to: "gram" },
    { value: "1", from: "ounce", to: "gram" },
  ],
  pressure: [
    { value: "1", from: "bar", to: "kilopascal" },
    { value: "1", from: "atmosphere", to: "kilopascal" },
    { value: "30", from: "psi", to: "bar" },
  ],
  temperature: [
    { value: "0", from: "celsius", to: "fahrenheit" },
    { value: "32", from: "fahrenheit", to: "celsius" },
    { value: "0", from: "celsius", to: "kelvin" },
  ],
};

export const COORDINATE_FORMATS = [
  { id: "dd", label: "DD" },
  { id: "dms", label: "DMS" },
  { id: "ddm", label: "DDM" },
  { id: "mgrs", label: "MGRS" },
  { id: "utm", label: "UTM / UPS" },
  { id: "gars", label: "GARS" },
  { id: "georef", label: "GEOREF" },
];

export const OUTPUT_FORMATS = [
  ["dd", "DD"],
  ["dms", "DMS"],
  ["ddm", "DDM"],
  ["mgrs", "MGRS"],
  ["utmUps", "UTM / UPS"],
  ["gars", "GARS"],
  ["georef", "GEOREF"],
];
